spring.application.name=auth-Authorization

spring.datasource.url=jdbc:postgresql://localhost:5432/authtest
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.error.include-stacktrace=always
logging.level.org.springframework=DEBUG

jwt.secretKey=asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7z

refreshToken = 300